=== mszhanghm/jax_archive_site_dev/_includes/faculty/IA_schema.json
{
 "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "id": "http://archive.jax.org/faculty",
    "properties": {
        "archiveFolderPath": {
            "type": "string"
        },
        "archiveLeaseReviewDate": {
            "type": "string"
        },
        "checksumFile": {
            "type": "string"
        },
        "compressedByIT": {
            "type": "string"
        },
        "contactEmail": {
            "type": "string"
        },
        "dataType": {
            "type": "string"
        },
        "dateArchived": {
            "type": "string"
        },
        "dateUpdated": {
            "type": "string"
        },
        "fileList": {
            "type": "string"
        },
        "grantIdentifier": {
            "type": "string"
        },
        "isControlled": {
            "type": "string"
        },
        "managerName": {
            "type": "string"
        },
        "managerUserId": {
            "type": "string"
        },
        "notes": {
            "type": "string"
        },
        "projectName": {
            "type": "string"
        },
        "sourceFolderPath": {
            "type": "string"
        },
        "tarFiles": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "userId": {
            "type": "string"
        },
        "userName": {
            "type": "string"
        },
        "version": {
            "type": "string"
        }
    },
    "type": "object"
}

=== mszhanghm/jax_archive_site_dev/_includes/faculty/IA_metadata.json
{
  "version":"1.0",
  "contactEmail":"investigator e-mail",
  "userName": "Firstname Lastname",
  "managerName": "Firstname Lastname",
  "dateArchived": "YYYY-MM-DD",
  "dateUpdated": "YYYY-MM-DD",
  "userId": "jaxid",
  "managerUserId":"jaxid",
  "sourceFolderPath":"",
  "grantIdentifier":"Strings:separatedBy:colons",
  "projectName":"project-name:string",
  "archiveLeaseReviewDate":"data archived + 1 year",
  "dataType":"type of data - tags separatedBy : sequence:research:images",
  "isControlled":"list of controlled separatedBy colon HIPPA:PHI, or N",
  "compressedByIT":"Y/N",
  "notes": "any notes provided by investigator",
  "archiveFolderPath": "/<ctartico/bhartico>/<s-data>/faculty/investigatorid/jaxid/yyyymmdd/projectname>/",
  "checksumFile":"/pathonarchive",
  "fileList":"/pathonarchive",
  "tarFiles": [
    "data-001.tar.gz",
    "<projectname>-<001>.tar.gz"
  ]
}
