=== mszhanghm/jax_archive_site_dev/_includes/sequence/LEGACY/RIT_legacy_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "id": "http://example.com/example.json",
    "properties": {
        "archivedFolderSize": {
            "type": "integer"
        },
        "archivedPath": {
            "type": "string"
        },
        "checksumFile": {
            "type": "string"
        },
        "customerProjectName": {
            "type": "string"
        },
        "dateArchived": {
            "type": "string"
        },
        "dateDelivered": {
            "type": "string"
        },
        "dateProjectOpened": {
            "type": "string"
        },
        "dateUpdated": {
            "type": "string"
        },
        "deliveryPath": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "density": {
            "type": "string"
        },
        "error": {
            "type": "string"
        },
        "fileList": {
            "type": "string"
        },
        "flowCellId": {
            "type": "string"
        },
        "grantID": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "groupName": {
            "type": "string"
        },
        "gtProjectName": {
            "type": "string"
        },
        "instrument": {
            "type": "string"
        },
        "investigatorID": {
            "type": "string"
        },
        "investigatorName": {
            "type": "string"
        },
        "isControlledData": {
            "type": "string"
        },
        "labAssociation": {
            "type": "string"
        },
        "labLocation": {
            "type": "string"
        },
        "moleculeType": {
            "type": "string"
        },
        "notes": {
            "type": "string"
        },
        "pctClusterPF": {
            "type": "string"
        },
        "pctErrorRate": {
            "type": "string"
        },
        "pctPhiX": {
            "type": "string"
        },
        "pctQ30": {
            "type": "string"
        },
        "projectId": {
            "type": "string"
        },
        "readsM": {
            "type": "string"
        },
        "runCompleteDate": {
            "type": "string"
        },
        "runId": {
            "type": "string"
        },
        "runStartDate": {
            "type": "string"
        },
        "runType": {
            "type": "string"
        },
        "samples": {
            "items": {
                "properties": {
                    "cellCount": {
                        "type": "string"
                    },
                    "concentration": {
                        "type": "string"
                    },
                    "customerSampleName": {
                        "type": "string"
                    },
                    "erccSpike": {
                        "type": "string"
                    },
                    "fastqFileName": {
                        "type": "string"
                    },
                    "flowcellLane": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "materialType": {
                        "type": "string"
                    },
                    "protocol": {
                        "type": "string"
                    },
                    "rawFileType": {
                        "type": "string"
                    },
                    "sampleID": {
                        "type": "string"
                    },
                    "sampleName": {
                        "type": "string"
                    },
                    "sampleType": {
                        "type": "string"
                    },
                    "species": {
                        "type": "string"
                    },
                    "totalReads": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "type": "array"
        },
        "softwareInformation": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "sourceSystem": {
            "type": "string"
        },
        "sourcefolderSize": {
            "type": "integer"
        },
        "submittedToExternal": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "totalYield": {
            "type": "string"
        },
        "userFirstName": {
            "type": "string"
        },
        "userID": {
            "type": "string"
        },
        "userLastName": {
            "type": "string"
        },
        "version": {
            "type": "string"
        }
    },
    "type": "object"
}

=== mszhanghm/jax_archive_site_dev/_includes/sequence/LEGACY/RIT_legacy_metadata.json
{
  "version": "1.0",
  "sourceSystem": "helix",
  "deliveryPath": [
    "/seqdata/Runs/151223_M03341_0055_000000000-AL042",
    "/gt/run/folder/path,",
    "/other/paths for this data"
  ],
  "sourcefolderSize": 1232435435,
  "archivedFolderSize": 234545645,
  "archivedPath": "/archive/GT/legacy/151223_M03341_0055_000000000-AL042",
  "investigatorName": "Name",
  "investigatorID": "pijaxid",
  "userFirstName": "Danjun",
  "userLastName": "Wang",
  "userID": "Lab Member jaxid",
  "groupName": "groupid e.g. user-lab",
  "labLocation": "BH",
  "labAssociation": "internal",
  "isControlledData": "no",
  "submittedToExternal": [
    "sra2342",
    "sdf23423"
  ],
  "grantID": [
    "grant2342",
    "gramt2342"
  ],
  "dateArchived": "YYYY-MM-DD",
  "dateUpdated": "YYYY-MM-DD",
  "error": "any errors in processing",
  "checksumFile": "file with checksums for all files in folder",
  "fileList": "file with list of all files being delivered in folder",
  "gtProjectName": "GT Project Name Alphanumeric",
  "projectId": "16TST-005-OUP-run3 - Project ID",
  "customerProjectName": "Customer Project Name Alphanumeric",
  "runId": "161216_K00384_0014_HG3FTBBXX",
  "runType": "run type",
  "dateProjectOpened": "YYYY-MM-DD",
  "runStartDate": "2016-12-16",
  "runCompleteDate": "2016-12-19",
  "dateDelivered": "2016-12-19",
  "flowCellId": "Flow Cell ID",
  "pctQ30": "83.47",
  "density": "235.5",
  "pctPhiX": "0.8",
  "readsM": "482.99",
  "totalYield": "826.63",
  "moleculeType": "rna seq",
  "pctErrorRate": "0.0009",
  "pctClusterPF": "7549.6",
  "instrument": "CT_Illumina_HiSeq4000_K00384",
  "softwareInformation": [
    "BCL2Fastq_2.17.123",
    "Another software with version"
  ],
  "notes": "Any notes useful for lab/research",
  "samples": [
    {
      "id": "1",
      "fastqFileName": "16TST-005-Fir_c30_SP3D_S__L004_R1_001.fastq.gz",
      "sampleID": "sarcoma2",
      "sampleName": "sarcoma2",
      "species": "Mouse",
      "concentration": "23423.23",
      "protocol": "23dfsf233f",
      "erccSpike": "233.2",
      "totalReads": "265934239",
      "rawFileType": "Fastq",
      "flowcellLane": "001",
      "customerSampleName": "cusomer name",
      "materialType": "whole organism",
      "sampleType": "library",
      "cellCount": "23243324.32"
    },
    {
      "id": "2",
      "fastqFileName": "16TST-003335-Fir_c30_SP3D_S__L004_R1_001.fastq.gz",
      "sampleID": "sarcoma2",
      "sampleName": "sarcoma2",
      "species": "Mouse",
      "concentration": "23423.23",
      "protocol": "23dfsf233f",
      "erccSpike": "233.2",
      "totalReads": "265934239",
      "rawFileType": "Fastq",
      "flowcellLane": "001",
      "customerSampleName": "cusomer name",
      "materialType": "whole organism",
      "sampleType": "library",
      "cellCount": "23243324.32"
    },
    {
      "id": "3",
      "fastqFileName": "16TST-03305-Fir_c30_SP3D_S__L004_R1_001.fastq.gz",
      "sampleID": "sarcoma2",
      "sampleName": "sarcoma2",
      "species": "Mouse",
      "concentration": "23423.23",
      "protocol": "23dfsf233f",
      "erccSpike": "233.2",
      "totalReads": "265934239",
      "rawFileType": "Fastq",
      "flowcellLane": "001",
      "customerSampleName": "cusomer name",
      "materialType": "whole organism",
      "sampleType": "library",
      "cellCount": "23243324.32"
    }
  ]
}
